function filename = getEstimationFilename(estimationPath, estimationName, estimationID)
% getEstimationFilename Returns the filename of a saved estimation result
%   filename = getEstimationFilename(estimationPath, estimationName, estimationID)
%   estimationPath: path to the folder containing estimation files
%   estimationName: base name of the estimation (e.g., 'Estimation_NKUS5425')
%   estimationID: unique ID string (e.g., generated by replace(char(datetime("now")), {'-',':',' '}, {'_','_','_'}))


if strcmpi(estimationID, 'latest')
    % Find all matching estimation files
    files = dir(fullfile(estimationPath, [estimationName '_*.mat']));
    if isempty(files)
        error('No estimation files found for %s in %s', estimationName, estimationPath);
    end
    % Sort by date
    [~, idx] = max([files.datenum]);
    filename = fullfile(estimationPath, files(idx).name);
else
    filename = fullfile(estimationPath, [estimationName '_' estimationID '.mat']);
    if ~isfile(filename)
        error('Estimation file not found: %s', filename);
    end
end

end
